# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'process_monitoring.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog_monitoring(object):
    def setupUi(self, dialog_monitoring):
        dialog_monitoring.setObjectName("dialog_monitoring")
        dialog_monitoring.resize(960, 720)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        dialog_monitoring.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(dialog_monitoring)
        self.gridLayout.setObjectName("gridLayout")
        self.scroll_area = QtWidgets.QScrollArea(dialog_monitoring)
        font = QtGui.QFont()
        font.setKerning(True)
        self.scroll_area.setFont(font)
        self.scroll_area.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scroll_area.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scroll_area.setLineWidth(0)
        self.scroll_area.setWidgetResizable(True)
        self.scroll_area.setObjectName("scroll_area")
        self.scroll_area_widget_contents = QtWidgets.QWidget()
        self.scroll_area_widget_contents.setGeometry(QtCore.QRect(0, 0, 938, 698))
        self.scroll_area_widget_contents.setObjectName("scroll_area_widget_contents")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.scroll_area_widget_contents)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 441, 651))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vert_layout_monitoring = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vert_layout_monitoring.setContentsMargins(0, 0, 0, 0)
        self.vert_layout_monitoring.setObjectName("vert_layout_monitoring")
        self.lbl_monitoring = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setKerning(True)
        self.lbl_monitoring.setFont(font)
        self.lbl_monitoring.setObjectName("lbl_monitoring")
        self.vert_layout_monitoring.addWidget(self.lbl_monitoring)
        self.hori_line_monitoring = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.hori_line_monitoring.setFrameShape(QtWidgets.QFrame.HLine)
        self.hori_line_monitoring.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.hori_line_monitoring.setObjectName("hori_line_monitoring")
        self.vert_layout_monitoring.addWidget(self.hori_line_monitoring)
        self.lbl_inv = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setUnderline(True)
        font.setKerning(True)
        self.lbl_inv.setFont(font)
        self.lbl_inv.setObjectName("lbl_inv")
        self.vert_layout_monitoring.addWidget(self.lbl_inv)
        self.grid_layout_add_inv = QtWidgets.QGridLayout()
        self.grid_layout_add_inv.setObjectName("grid_layout_add_inv")
        self.lbl_add_inv_recipe = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_add_inv_recipe.setObjectName("lbl_add_inv_recipe")
        self.grid_layout_add_inv.addWidget(self.lbl_add_inv_recipe, 0, 0, 1, 1)
        self.lbl_add_inv_volume = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_add_inv_volume.setObjectName("lbl_add_inv_volume")
        self.grid_layout_add_inv.addWidget(self.lbl_add_inv_volume, 1, 0, 1, 1)
        self.combo_box_add_inv_recipe = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.combo_box_add_inv_recipe.setObjectName("combo_box_add_inv_recipe")
        self.combo_box_add_inv_recipe.addItem("")
        self.combo_box_add_inv_recipe.addItem("")
        self.combo_box_add_inv_recipe.addItem("")
        self.grid_layout_add_inv.addWidget(self.combo_box_add_inv_recipe, 0, 1, 1, 1)
        self.line_edit_add_inv_volume = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.line_edit_add_inv_volume.setObjectName("line_edit_add_inv_volume")
        self.grid_layout_add_inv.addWidget(self.line_edit_add_inv_volume, 1, 1, 1, 1)
        self.vert_layout_monitoring.addLayout(self.grid_layout_add_inv)
        self.hori_line_inv = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.hori_line_inv.setFrameShape(QtWidgets.QFrame.HLine)
        self.hori_line_inv.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.hori_line_inv.setObjectName("hori_line_inv")
        self.vert_layout_monitoring.addWidget(self.hori_line_inv)
        self.lbl_ongoing_processes = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setUnderline(True)
        font.setKerning(True)
        self.lbl_ongoing_processes.setFont(font)
        self.lbl_ongoing_processes.setObjectName("lbl_ongoing_processes")
        self.vert_layout_monitoring.addWidget(self.lbl_ongoing_processes)
        self.lbl_ongoing_processes_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_ongoing_processes_2.setText("")
        self.lbl_ongoing_processes_2.setObjectName("lbl_ongoing_processes_2")
        self.vert_layout_monitoring.addWidget(self.lbl_ongoing_processes_2)
        self.hori_line_ongoing_processes = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.hori_line_ongoing_processes.setFrameShape(QtWidgets.QFrame.HLine)
        self.hori_line_ongoing_processes.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.hori_line_ongoing_processes.setObjectName("hori_line_ongoing_processes")
        self.vert_layout_monitoring.addWidget(self.hori_line_ongoing_processes)
        self.lbl_start_process = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setUnderline(True)
        font.setKerning(True)
        self.lbl_start_process.setFont(font)
        self.lbl_start_process.setObjectName("lbl_start_process")
        self.vert_layout_monitoring.addWidget(self.lbl_start_process)
        self.grid_layout_start_process = QtWidgets.QGridLayout()
        self.grid_layout_start_process.setObjectName("grid_layout_start_process")
        self.lbl_new_recipe = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_new_recipe.setObjectName("lbl_new_recipe")
        self.grid_layout_start_process.addWidget(self.lbl_new_recipe, 1, 0, 1, 1)
        self.combo_box_new_brew_process = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.combo_box_new_brew_process.setObjectName("combo_box_new_brew_process")
        self.combo_box_new_brew_process.addItem("")
        self.combo_box_new_brew_process.addItem("")
        self.combo_box_new_brew_process.addItem("")
        self.combo_box_new_brew_process.addItem("")
        self.grid_layout_start_process.addWidget(self.combo_box_new_brew_process, 0, 1, 1, 1)
        self.combo_box_new_recipe = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.combo_box_new_recipe.setObjectName("combo_box_new_recipe")
        self.combo_box_new_recipe.addItem("")
        self.combo_box_new_recipe.addItem("")
        self.combo_box_new_recipe.addItem("")
        self.grid_layout_start_process.addWidget(self.combo_box_new_recipe, 1, 1, 1, 1)
        self.combo_box_new_tank = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.combo_box_new_tank.setObjectName("combo_box_new_tank")
        self.combo_box_new_tank.addItem("")
        self.combo_box_new_tank.addItem("")
        self.combo_box_new_tank.addItem("")
        self.combo_box_new_tank.addItem("")
        self.combo_box_new_tank.addItem("")
        self.combo_box_new_tank.addItem("")
        self.combo_box_new_tank.addItem("")
        self.combo_box_new_tank.addItem("")
        self.combo_box_new_tank.addItem("")
        self.grid_layout_start_process.addWidget(self.combo_box_new_tank, 2, 1, 1, 1)
        self.lbl_new_brew_process = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_new_brew_process.setObjectName("lbl_new_brew_process")
        self.grid_layout_start_process.addWidget(self.lbl_new_brew_process, 0, 0, 1, 1)
        self.line_edit_new_volume = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.line_edit_new_volume.setObjectName("line_edit_new_volume")
        self.grid_layout_start_process.addWidget(self.line_edit_new_volume, 3, 1, 1, 1)
        self.lbl_new_tank = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_new_tank.setObjectName("lbl_new_tank")
        self.grid_layout_start_process.addWidget(self.lbl_new_tank, 2, 0, 1, 1)
        self.lbl_new_volume = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_new_volume.setObjectName("lbl_new_volume")
        self.grid_layout_start_process.addWidget(self.lbl_new_volume, 3, 0, 1, 1)
        self.vert_layout_monitoring.addLayout(self.grid_layout_start_process)
        self.btn_start_process = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_start_process.setObjectName("btn_start_process")
        self.vert_layout_monitoring.addWidget(self.btn_start_process, 0, QtCore.Qt.AlignLeft)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vert_layout_monitoring.addItem(spacerItem)
        self.scroll_area.setWidget(self.scroll_area_widget_contents)
        self.gridLayout.addWidget(self.scroll_area, 0, 0, 1, 1)

        self.retranslateUi(dialog_monitoring)
        QtCore.QMetaObject.connectSlotsByName(dialog_monitoring)

    def retranslateUi(self, dialog_monitoring):
        _translate = QtCore.QCoreApplication.translate
        dialog_monitoring.setWindowTitle(_translate("dialog_monitoring", "Barnaby\'s Brewhouse: Process Monitoring"))
        self.lbl_monitoring.setText(_translate("dialog_monitoring", "Process Monitoring"))
        self.lbl_inv.setText(_translate("dialog_monitoring", "Inventory"))
        self.lbl_add_inv_recipe.setText(_translate("dialog_monitoring", "Beer Recipe:"))
        self.lbl_add_inv_volume.setText(_translate("dialog_monitoring", "Volume (L):"))
        self.combo_box_add_inv_recipe.setItemText(0, _translate("dialog_monitoring", "Organic Red Helles"))
        self.combo_box_add_inv_recipe.setItemText(1, _translate("dialog_monitoring", "Organic Pilsner"))
        self.combo_box_add_inv_recipe.setItemText(2, _translate("dialog_monitoring", "Organic Dunkel"))
        self.lbl_ongoing_processes.setText(_translate("dialog_monitoring", "Ongoing Processes"))
        self.lbl_start_process.setText(_translate("dialog_monitoring", "Start Process"))
        self.lbl_new_recipe.setText(_translate("dialog_monitoring", "Beer Recipe:"))
        self.combo_box_new_brew_process.setItemText(0, _translate("dialog_monitoring", "Hot Brew"))
        self.combo_box_new_brew_process.setItemText(1, _translate("dialog_monitoring", "Fermentation"))
        self.combo_box_new_brew_process.setItemText(2, _translate("dialog_monitoring", "Conditioning and Carbonation"))
        self.combo_box_new_brew_process.setItemText(3, _translate("dialog_monitoring", "Bottling and Labelling"))
        self.combo_box_new_recipe.setItemText(0, _translate("dialog_monitoring", "Organic Red Helles"))
        self.combo_box_new_recipe.setItemText(1, _translate("dialog_monitoring", "Organic Pilsner"))
        self.combo_box_new_recipe.setItemText(2, _translate("dialog_monitoring", "Organic Dunkel"))
        self.combo_box_new_tank.setItemText(0, _translate("dialog_monitoring", "Albert (1000 L, Fermenter/Conditioner)"))
        self.combo_box_new_tank.setItemText(1, _translate("dialog_monitoring", "Brigadier (800 L, Fermenter/Conditioner)"))
        self.combo_box_new_tank.setItemText(2, _translate("dialog_monitoring", "Camilla (1000 L, Fermenter/Conditioner)"))
        self.combo_box_new_tank.setItemText(3, _translate("dialog_monitoring", "Dylon (800 L, Fermenter/Conditioner)"))
        self.combo_box_new_tank.setItemText(4, _translate("dialog_monitoring", "Emily (1000 L, Fermenter/Conditioner)"))
        self.combo_box_new_tank.setItemText(5, _translate("dialog_monitoring", "Florence (800 L, Fermenter/Conditioner)"))
        self.combo_box_new_tank.setItemText(6, _translate("dialog_monitoring", "Gertrude (680 L, Conditioner)"))
        self.combo_box_new_tank.setItemText(7, _translate("dialog_monitoring", "Harry (680 L, Conditioner)"))
        self.combo_box_new_tank.setItemText(8, _translate("dialog_monitoring", "R2D2 (800 L, Fermenter)"))
        self.lbl_new_brew_process.setText(_translate("dialog_monitoring", "Brew Process:"))
        self.lbl_new_tank.setText(_translate("dialog_monitoring", "Tank:"))
        self.lbl_new_volume.setText(_translate("dialog_monitoring", "Volume (L):"))
        self.btn_start_process.setText(_translate("dialog_monitoring", "Start Process"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialog_monitoring = QtWidgets.QDialog()
    ui = Ui_dialog_monitoring()
    ui.setupUi(dialog_monitoring)
    dialog_monitoring.show()
    sys.exit(app.exec_())
